nuget:
  account_feed: true

version: 2.0.{build}

before_build:
 - nuget restore
 - cmd: set BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%

deploy:
 - provider: Environment
   name: NugetPublish
   on:
    branch: master
